### ISSUE TITLE
txt soubor lze pridat do systemoveho playlistu, ale neprehraje se.

### ISSUE THREAD

**Issue by paja-ntk** [techlib/indoktrinator#26]
txt soubor lze pridat do systemoveho playlistu, ale neprehraje se.

**Comment by mordae** [comment]
Nerozumím problému. Zobrazí v playlistu jako video soubor?

**Comment by mordae** [comment]
Pokud se jedná o #12, tak jsme nestihli implementovat.

**Comment by mordae** [comment]
OK, `ffprobe` nahlásí, že se jedná o video. Pokud zkusím textový soubor přehrát pomocí `ffplay`, tak bohužel uspěji. GStreamer už ale stejný názor nemá, takže se na televizi nic nezobrazí. Přidáme další kontrolu do `indoktrinator-probe`.
