### ISSUE TITLE
Nelze smazat zarizeni

### ISSUE THREAD

**Issue by paja-ntk** [techlib/indoktrinator#27]
Nelze smazat zarizeni.

**Comment by ZtF** [comment]
Muzes to prosim nejak priblizit? Neumim reprodukovat, mne mazat jdou.

**Comment by paja-ntk** [comment]
Mozna jen nemam prava.

**Comment by koudi** [comment]
Práva nejsou nijak oddelena

**Comment by ZtF** [comment]
Zarizeni, je-li videno a zachovano v pameti, se nesmaze ani pote, co jiz neni videno, je vytvoreno v DB a nasledne smazano. V pameti zustava i nadale.
