### ISSUE TITLE
Fix file scanner

### ISSUE THREAD

**Issue by koudi** [techlib/indoktrinator#9]
File scanner should follow specification:

- [x] There is no "root" playlist. Files in root of data folder should be ignored. Current behavior creates new playlist. This playlist has empty name, so it doesn't even work properly in UI.

- [x] Only top-level folders in root data folder should create playlists. Currently, file structure such as   `/data/folder1/subfolder` creates playlists _folder1_ and _folder1/subfolder_. All subfolders and its contents should be part of _folder1_ playlist.

- [x] File scanner should not create any m3u8 files. Currently index.m3u8 is always created in data root

- [ ] Files in folder should be ordered by their filename. Currently, all items have `position = 0` in db

- [ ] `index.m3u8` files are ignored

- [x] Deleting folder in data root does not delete playlist and crashes scanner with `IOError('File does not exists')`

- [x] Indoktrinator will not remove files that were deleted when it was not running.

- [ ] Harvester crashes when files are renamed rapidly in a loop. It attempts to save multiple playlists under the same name. For example `(a -> b -> a)`.

**Comment by mordae** [comment]
We won't be fixing the old file scanner. I will create separate tickets for the individual outstanding features.
